numbers: main.o sum.o sum_squares.o prime.o
	gcc main.o sum.o sum_squares.o prime.o -o numbers

sum.o: sum.c
	gcc -c sum.c

sum_squares.o: sum_squares.c
	gcc -c sum_squares.c

prime.o: prime.c
	gcc -c prime.c

main.o: main.c
	gcc -c main.c
